-- database
CREATE DATABASE `aav` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;

CREATE DATABASE `aps` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;

CREATE DATABASE `sp-dev` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;



